# -*- coding: utf-8 -*-
"""Mesh_segmentation_Pytorch_Test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ztYC_J9CbetqWKejk3jEbdvfHXxXYDZd

test_trained_mlps.py -- test the trained per-surface MLPs on a new subject.

One model per head surface: mlp_cell01.pt ... mlp_cell20.pt. Each checkpoint
holds its own weights, its own feature normalisation (mean / std of the
training subjects) and its own decision threshold.

This script loads all of them, applies each one to the matching surface of the
test subject, prints the metrics and saves the predictions for MATLAB.

Run it with the paths in the CONFIG block below:

    python test_trained_mlps.py

or override any of them on the command line:

    python test_trained_mlps.py --model-dir Trained_models --test-dir Testing_dataset \
                                --subject HC023 --results-dir Testing_Results

Self-contained: the MLP class and the loaders are defined here, so no other
file is needed.
"""

import argparse
import os

import numpy as np
import torch
import torch.nn as nn
from scipy.io import loadmat, savemat

from google.colab import drive
drive.mount('/content/drive')

# ----------------------------------------------------------------- CONFIG
model_dir   = '/content/drive/MyDrive/Mesh_segmentation_new/Trained_models'
test_dir    = '/content/drive/MyDrive/Mesh_segmentation_new/Testing_dataset'
results_dir = '/content/drive/MyDrive/Mesh_segmentation_new/Testing_Results'
subject     = 'HC023'
# -------------------------------------------------------------------------

features_file = os.path.join(test_dir, f'{subject}_features_vertices.mat')
labels_file   = os.path.join(test_dir, f'{subject}_mesh_gt.mat')
os.makedirs(results_dir, exist_ok=True)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

class MLP(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes, dropout=0.2):
        super(MLP, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.fc2 = nn.Linear(hidden_size, hidden_size)
        self.fc3 = nn.Linear(hidden_size, hidden_size)
        self.fc4 = nn.Linear(hidden_size, num_classes)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(p=dropout)

    def forward(self, x):
        x = self.dropout(self.relu(self.fc1(x)))
        x = self.dropout(self.relu(self.fc2(x)))
        x = self.dropout(self.relu(self.fc3(x)))
        return self.fc4(x)

fv = loadmat(features_file)['features_vertices']
gt = loadmat(labels_file)['Label_vertices']
n_surfaces = fv.size

pred_cells = np.empty((n_surfaces, 1), dtype=object)
prob_cells = np.empty((n_surfaces, 1), dtype=object)
idx_cells  = np.empty((n_surfaces, 1), dtype=object)
metrics    = []

for c in range(1, n_surfaces + 1):
    ckpt = torch.load(os.path.join(model_dir, f'mlp_cell{c:02d}.pt'),
                      map_location='cpu', weights_only=True)

    model = MLP(ckpt['input_size'], ckpt['hidden_size'],
                ckpt['num_classes'], ckpt['dropout'])
    model.load_state_dict(ckpt['state_dict'])
    model.to(device).eval()                         # dropout OFF

    X = np.asarray(fv.ravel()[c - 1], dtype=np.float64)
    y = np.zeros(X.shape[0], dtype=np.int64)
    y[np.asarray(gt.ravel()[c - 1]).ravel().astype(int) - 1] = 1

    Xs = (X - ckpt['scaler_mean'].numpy()) / ckpt['scaler_scale'].numpy()
    with torch.no_grad():
        logits = model(torch.tensor(Xs, dtype=torch.float32, device=device))
        prob = torch.softmax(logits, dim=1)[:, 1].cpu().numpy()
    pred = (prob >= ckpt['threshold']).astype(np.int64)

    tp = int(np.sum((pred == 1) & (y == 1)))
    fp = int(np.sum((pred == 1) & (y == 0)))
    fn = int(np.sum((pred == 0) & (y == 1)))
    tn = int(np.sum((pred == 0) & (y == 0)))
    acc  = (tp + tn) / (tp + tn + fp + fn)
    rec  = tp / max(tp + fn, 1)
    prec = tp / max(tp + fp, 1)
    fpr  = fp / max(fp + tn, 1)

    pred_cells[c - 1, 0] = pred.reshape(-1, 1)
    prob_cells[c - 1, 0] = prob.reshape(-1, 1)
    idx_cells[c - 1, 0]  = (np.flatnonzero(pred) + 1).reshape(-1, 1)   # MATLAB 1-based
    metrics.append([c, acc, rec, prec, fpr, tp, fp, fn, tn])

    print(f'[surface {c:2d}] acc {acc*100:5.2f}%  recall {rec*100:5.2f}%  '
          f'precision {prec*100:5.2f}%  FPR {fpr*100:5.2f}%  '
          f'TP {tp:5d}  FP {fp:6d}  FN {fn:5d}')

metrics = np.array(metrics, dtype=np.float64)
print('\nmean:  acc {:.2f}%  recall {:.2f}%  precision {:.2f}%  FPR {:.2f}%'
      .format(*(100 * metrics[:, 1:5].mean(axis=0))))

out_path = os.path.join(results_dir, f'{subject}_pred.mat')
savemat(out_path, {'predicted': pred_cells,
                   'predicted_prob': prob_cells,
                   'predicted_idx': idx_cells,
                   'metrics': metrics})
print('saved', out_path)