function mni_normalization_brainstorm(subjectName, mriFilePath)
    % Input validation
    if nargin < 2
        error('Two inputs are required: subjectName and mriFilePath');
    end

    % Start a new report
    sFiles = [];
    bst_report('Start', sFiles);

    % Process: Import MRI
    sFiles = bst_process('CallProcess', 'process_import_mri', sFiles, [], ...
        'subjectname', subjectName, ...
        'mrifile',     {mriFilePath, 'Nifti1'}, ...
        'nas',         [0, 0, 0], ...
        'lpa',         [0, 0, 0], ...
        'rpa',         [0, 0, 0], ...
        'ac',          [0, 0, 0], ...
        'pc',          [0, 0, 0], ...
        'ih',          [0, 0, 0]);

    % Process: MNI normalization
    sFiles = bst_process('CallProcess', 'process_mni_normalize', sFiles, [], ...
        'subjectname', subjectName, ...
        'method',      'maff8', ...  % Affine registration using SPM mutual information algorithm
        'uset2',       0);

    % Save and display report
    ReportFile = bst_report('Save', sFiles);
    bst_report('Open', ReportFile);
end